name: PR Validation
on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.json'
    types: [opened, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download PR Checker
      run: |
        curl -L -o pr-checker -OJ https://repo.ghany.fyi/api/packages/OpenCorp/generic/pr-checker-linux-amd64/0.0.3/pr-checker-linux-amd64
        curl -L -o checker_config.json -OJ https://repo.ghany.fyi/OpenCorp/PRchecker/raw/branch/main/checker_config.json
        chmod +x pr-checker

    - name: Run Validation
      run: |
        ./pr-checker -r $GITHUB_WORKSPACE -c ./checker_config.json \
          -b ${{ github.event.pull_request.base.sha }} \
          -h ${{ github.event.pull_request.head.sha }} \
          -v -t 50s 2>error.log
      continue-on-error: true
      id: validation

    - name: Comment PR on Failure
      if: steps.validation.outcome == 'failure'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issue_number = context.payload.pull_request.number;
          const stderr = process.env.stderr;
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue_number,
            body: `### Validation failed, check logs! ###`
          });

    - name: Fail if validation failed
      if: steps.validation.outcome == 'failure'
      run: exit 1
